---
var_lube_logger_compose_with_default_network_input_filename: "lube-logger_compose-with-default-network.j2"
var_lube_logger_compose_with_default_network_output_filename: "compose-with-default-network.yaml"
var_lube_logger_compose_with_swag_input_filename: "lube-logger_compose-with-swag.j2"
var_lube_logger_compose_with_swag_output_filename: "compose-with-swag.yaml"
var_lube_logger_container_image_version: "v1.6.1"
var_lube_logger_container_name: "lubelog-ui"
var_lube_logger_container_port: "9001"
var_lube_logger_container_username: ""
var_lube_logger_docker_compose_directory: "~/Container-Apps/LubeLogger"
var_lube_logger_docker_compose_input_filename: "lube-logger_docker-compose.j2"
var_lube_logger_docker_compose_output_filename: "docker-compose.yaml"
var_lube_logger_postgres_container_image_version: "17"
var_lube_logger_postgres_container_name: "lubelog-db"
var_lube_logger_postgres_db: "lubelogdb"
var_lube_logger_postgres_password: "changemeplease"
var_lube_logger_postgres_user: "lubelogger"
var_lube_logger_project_name: "lube_log"
var_lube_logger_state: "present"
var_lube_logger_swag_cloudflare_api_token: ""
var_lube_logger_swag_cloudflare_ini_input_filename: "cloudflare-ini.j2"
var_lube_logger_swag_container_image_version: "amd64-latest"
var_lube_logger_swag_container_name: "lubelog-swag"
var_lube_logger_swag_email_address: ""
var_lube_logger_swag_tld: ""
var_lube_logger_swag_timezome: "America/Detroit"
var_should_delete_docker_compose_file: false
var_should_deploy_with_swag_container: false
var_should_test_docker_compose_copy_only: false
